[package]
name = "galactic-errands"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9"
noisy_bevy = "0.2"
console_error_panic_hook = "0.1"

